In [13]:
import numpy as np
#Create 1D array
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [14]:
#accessing elements from array
arr1[2]

3

In [3]:
#change an element from array
arr1[2]=5

In [4]:
arr1

array([1, 2, 5])

In [15]:
#create 2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
#check the shape of array
print("The Shape is 2 rows and 3 columns:",arr2.shape)

The Shape is 2 rows and 3 columns: (2, 3)


In [17]:
#Accessing the elements from array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [18]:
#array of tye string
arr3=np.array(['India','China','USA','Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [10]:
arr3[1]

'China'

In [19]:
#Array of evenly spaced values within specified interval
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
#Array of evenly spaced number in specified interval
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [21]:
#Array of random values between 0 and 1 in a given shape
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.68743134 0.28345407 0.30146329 0.85829849 0.13257618 0.96700518
 0.07727837 0.24869621 0.0660331  0.80302311]


[[0.00784719 0.76324312 0.62554828 0.29258244]
 [0.91266123 0.58837056 0.53481524 0.69452288]
 [0.50191419 0.90627598 0.15145774 0.00687948]]


In [22]:
#Array of constant values in a given shape
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [23]:
#Create an array by repitition
#repeat each element of an array by a specified number of times
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [24]:
#Repeat an array by a specified number of times
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [26]:
#Create an identity matrix with eye
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#Create an identity matrix with identity
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#create 5*5 array for random no between 0 & 1
arr=np.random.rand(5,5)
print(arr)

[[0.53370959 0.51204123 0.79177402 0.36095497 0.6422525 ]
 [0.59392275 0.96946228 0.06009808 0.06352568 0.97423012]
 [0.83610295 0.52613131 0.404734   0.16389741 0.92579069]
 [0.37806913 0.13370278 0.19090199 0.90276333 0.67118553]
 [0.67721607 0.93061639 0.42298494 0.06294356 0.29564897]]


In [29]:
#Sum along the column
print(np.sum(arr,axis=0))

[3.0190205  3.07195398 1.87049304 1.55408495 3.5091078 ]


In [30]:
#Sum along the row
print(np.sum(arr,axis=1))

[2.84073231 2.66123891 2.85665635 2.27662277 2.38940993]


In [31]:
#calculate mean,median,sd and variance
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5209864110079158
0.5261313090855765
0.3007818145128289
0.09046969994162982


In [32]:
#Sort an array
arr=np.random.rand(5,5)
print(arr)

[[0.92813219 0.7821089  0.67448749 0.64778408 0.74405194]
 [0.6848015  0.81987876 0.26358057 0.3958675  0.30573526]
 [0.99407692 0.42603556 0.66873992 0.55575184 0.07126615]
 [0.93579034 0.02088296 0.45985282 0.31092995 0.94877228]
 [0.55731563 0.79004187 0.33507373 0.54679741 0.49070411]]


In [36]:
#Sort along the row
print(np.sort(arr,axis=1))

[[0.64778408 0.67448749 0.74405194 0.7821089  0.92813219]
 [0.26358057 0.30573526 0.3958675  0.6848015  0.81987876]
 [0.07126615 0.42603556 0.55575184 0.66873992 0.99407692]
 [0.02088296 0.31092995 0.45985282 0.93579034 0.94877228]
 [0.33507373 0.49070411 0.54679741 0.55731563 0.79004187]]


In [42]:
#Append elements to array
arr=np.array([4,5,6,7])

In [39]:
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [40]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [43]:
#Delete multiple elements
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [44]:
#Combine and split an array
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])

In [47]:
#Combine the array items by column
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [48]:
#Combine the array items by row
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
